services:
  db:
    image: public.ecr.aws/docker/library/postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5342:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:Z

volumes:
  db_data: