apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: public.ecr.aws/bitnami/minio:latest
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
#          args:
#            - server
#            - /data
#            - --console-address
#            - :9001
          env:
            - name: MINIO_ROOT_USER
              value: kopi
            - name: MINIO_ROOT_PASSWORD
              value: passwordkopi
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: 1000m

---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30082
      name: public-port
    - port: 9001
      targetPort: 9001
      nodePort: 30083
      name: internal-port